def gitCommit=''
def dockerUser='<type_yours>'
def dockerPassword='<type_yours>'
def dockerRegistry='<type_yours>'

node{
    stage('Checkout'){
        checkout scm
    }

    stage('Compile and Unit Tests'){
        echo 'compilando...'
    }

    stage('Build Docker Image'){
        sh ''
    }

    stage('Tests Component'){
        dir('tests-component'){
             sh './test.sh'
        }
    }

    stage('Tag Image'){
        gitCommit = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
        sh "docker tag yacarini.demo.app ${dockerRegistry}/demo-jenkins:${gitCommit}"
    }

    stage('Publish Image'){
        sh "docker login --username=${dockerUser} --password=${dockerPassword} ${dockerRegistry}"
        sh "docker push ${dockerRegistry}/demo-jenkins:${gitCommit}"
        sh "docker logout ${dockerRegistry}"
    }

    stage('Deploy to Test'){
        echo "enviado a staging..."
    }

    stage('Performance Test'){
        echo "Performance"
    }
}

stage('Deploy to Prod'){
    input 'Are you sure?'
    node{
        echo "enviado a producción..."
    }
}
