---
- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install python-pip
  yum:
    name: python-pip
    state: latest

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest

- name: upgrade python
  yum:
    name: python*
    state: latest